# The goal definition (equivalent to the service request)
bool start
bool enable_filtering
float32 crop_x_min
float32 crop_x_max
float32 crop_y_min
float32 crop_y_max
float32 crop_z_min
float32 crop_z_max
bool enable_statistical_filter
bool statistical_std_ratio
bool enable_voxel_downsampling
float32 voxel_size
---
# The result definition (equivalent to the service response)
sensor_msgs/PointCloud2 point_cloud
bool success
string message
---
# The feedback definition (sent periodically during execution)
float32 progress
